### ISSUE TITLE
the cost of AWS practice

### ISSUE THREAD

**Issue by lmy931** [PacktPublishing/AWS-Certified-Machine-Learning-Specialty-MLS-C01-Certification-Guide#2]
Hi all,

We all know that AWS is not free. If I reproduce all operations, following the book step by step, how much would it cost roughly?

**Comment by lmy931** [comment]
Also, do you think reproducing the operations on AWS could be helpful for the exam?
For example, the 'Getting hands-on with Amazon Rekognition' in Chapter 2

I ask this question because the exam only contains choice questions, so is it still necessary to practice the AWS operations before attending the exam?

**Comment by deepesh-packt** [comment]
Hi @lmy931 
The book's author responded as follows:
If you have a free trial account for 12 months, then it will cost nothing.  If you have crossed those 12 months, then it would cost 50-60$  for the entire book and it may vary based on the usage. It is not mandatory to have the hands-on before the exam, but it is good to practice the examples before the exam. It gives you an in-depth idea about the services. For Chapter 2 examples, it is more important to learn the different features of the services. If you can practice them via different APIs, then it's a plus. If you don't want to practice them, then please read the code comments and their usage from API documentation. Again, it is not required to learn each and every API.

Regarding the "practicing" question, indeed, AWS exams are multiple choice, so the candidate does not need to implement any solution during the exam. However, It is absolutely recommended not only practice, practice and practice, but also read related AWS papers before doing the exam, specially If the candidate does not have working experience on AWS services.
