### ISSUE TITLE
EFS should be a private service, question 10 in Chapter 5

### ISSUE THREAD

**Issue by lmy931** [PacktPublishing/AWS-Certified-Machine-Learning-Specialty-MLS-C01-Certification-Guide#3]
Hi, I am doing the questions in Chapter 5. I have a small doubt about the given answer to question 10.

Question 10: Is EFS a private service?
I think the answer is **Yes**, while the answer given by the book is '**No**, it is a public service'.

I did some research from the AWS doc, and I found the EFS should be mounted in the VPC, which means it should be a private service.

**Comment by ArjunVarma39** [comment]
Hi @lmy931 

Here is the feedback shared by the author:

Apologies for the confusion in the book. Question number 10 , Chapter 5. 

Amazon EFS is a Private Service, by default it is isolated to the VPC in which it is provisioned into. EFS is part of the AWS Private Zone.

Thank you!
